### ISSUE TITLE
[data-row-edit] Editing a reference doesn't show the table

### ISSUE THREAD

**Issue by jelmerveen** [molgenis/molgenis-frontend#521] opened 2021-02-05 10:26 UTC
### How to Reproduce
Use new forms, go to a table with an xref field
change it

Example table: sys_negotiator_NegotiatorEntityConfig
<img width="870" alt="Screenshot 2021-02-05 at 15 08 19" src="https://user-images.githubusercontent.com/43730771/107044333-6d4dd380-67c4-11eb-9931-d77f433e26d9.png">

### Expected behavior
I see property (column) + table (entity)
<img width="1049" alt="Screenshot 2021-02-05 at 15 08 57" src="https://user-images.githubusercontent.com/43730771/107044271-59a26d00-67c4-11eb-90ed-c367eacffc58.png">
(the old state is not the best, but better than new forms)
### Observed behavior

I only see the property
<img width="1214" alt="Screenshot 2021-02-05 at 15 10 14" src="https://user-images.githubusercontent.com/43730771/107044231-4ee7d800-67c4-11eb-969c-0579ef4091c1.png">

**Comment by connoratrug** [comment] 2021-02-05 12:23
@jelmerveen , could you be a bit more specific, maybe link to an example, include a screenshot and add a rational for the expected behaviour

**Comment by jelmerveen** [comment] 2021-02-05 14:11
@connoratrug updated

**Comment by connoratrug** [comment] 2021-02-05 14:32
duplicate of https://github.com/molgenis/molgenis-frontend/issues/197

**Closed by connoratrug** 2021-02-05 14:32 UTC
